version: '3.1'
services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gateway:${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}-${CICD_EXECUTION_SEQUENCE}
    container_name: gateway
    ports:
      - "5000:80"
    volumes:
      - /www/wwwroot/gatewaySerilog:/app/Serilog
    networks:
      - gateway
networks:
 gateway:
  external: true