version: '3.1'
services:
  gateway:
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image: 121.40.220.126:81/net_core/gateway:${GIT_COMMIT}
    container_name: gateway
    ports:
      - "5000:80"
    volumes:
      - /www/wwwroot/gatewaySerilog:/app/Serilog
    networks:
      - gateway
networks:
 gateway:
  external: true
  name: gateway