version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: liunx
          hostID:
            - 5e11c054-1313-4620-8a95-e35fc1df6c18
        script:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
          - docker-compose.sh
        notify: []
        strategy:
          retry: '0'
